export default {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_MOVIES: 'FETCH_MOVIES',
    FETCH_MOVIE: 'FETCH_MOVIE',
    SET_MOVIE: 'SET_MOVIE',
    FETCH_REVIEWS: 'FETCH_REVIEWS',
    FETCH_REVIEW: 'FETCH_REVIEW',
    SET_REVIEW: 'SET_REVIEW'
}